name: Development Python workflow

on:
  push:
    branches:
    - Development

jobs:
  base-development:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./paaster-backend

    steps:
      - uses: actions/checkout@v2.3.2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude .git,__pycache__,docs/source/conf.py,old,build,dist
          # exit-zero treats all errors as warnings
          flake8 . --count --max-line-length=80 --statistics --exclude .git,__pycache__,docs/source/conf.py,old,build,dist
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install pyright
        run: npm install pyright -g
      - name: Run pyright
        run: pyright ./*
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
      - name: Run unit tests
        run: python ./run_tests.py